//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgOpenGPS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Vehicle : global::System.Configuration.ApplicationSettingsBase {
        
        private static Vehicle defaultInstance = ((Vehicle)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Vehicle())));
        
        public static Vehicle Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double setVehicle_antennaHeight {
            get {
                return ((double)(this["setVehicle_antennaHeight"]));
            }
            set {
                this["setVehicle_antennaHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double setVehicle_antennaPivot {
            get {
                return ((double)(this["setVehicle_antennaPivot"]));
            }
            set {
                this["setVehicle_antennaPivot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.8")]
        public double setVehicle_wheelbase {
            get {
                return ((double)(this["setVehicle_wheelbase"]));
            }
            set {
                this["setVehicle_wheelbase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double setVehicle_hitchLength {
            get {
                return ((double)(this["setVehicle_hitchLength"]));
            }
            set {
                this["setVehicle_hitchLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setVehicle_isPivotBehindAntenna {
            get {
                return ((bool)(this["setVehicle_isPivotBehindAntenna"]));
            }
            set {
                this["setVehicle_isPivotBehindAntenna"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setVehicle_isSteerAxleAhead {
            get {
                return ((bool)(this["setVehicle_isSteerAxleAhead"]));
            }
            set {
                this["setVehicle_isSteerAxleAhead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default Vehicle")]
        public string setVehicle_vehicleName {
            get {
                return ((string)(this["setVehicle_vehicleName"]));
            }
            set {
                this["setVehicle_vehicleName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double setVehicle_goalPointLookAhead {
            get {
                return ((double)(this["setVehicle_goalPointLookAhead"]));
            }
            set {
                this["setVehicle_goalPointLookAhead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public double setVehicle_maxSteerAngle {
            get {
                return ((double)(this["setVehicle_maxSteerAngle"]));
            }
            set {
                this["setVehicle_maxSteerAngle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int set_youTurnExtensionLength {
            get {
                return ((int)(this["set_youTurnExtensionLength"]));
            }
            set {
                this["set_youTurnExtensionLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double set_youToolWidths {
            get {
                return ((double)(this["set_youToolWidths"]));
            }
            set {
                this["set_youToolWidths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.9")]
        public double setVehicle_minTurningRadius {
            get {
                return ((double)(this["setVehicle_minTurningRadius"]));
            }
            set {
                this["setVehicle_minTurningRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double setVehicle_antennaOffset {
            get {
                return ((double)(this["setVehicle_antennaOffset"]));
            }
            set {
                this["setVehicle_antennaOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double set_youTurnDistanceFromBoundary {
            get {
                return ((double)(this["set_youTurnDistanceFromBoundary"]));
            }
            set {
                this["set_youTurnDistanceFromBoundary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double setVehicle_lookAheadMinimum {
            get {
                return ((double)(this["setVehicle_lookAheadMinimum"]));
            }
            set {
                this["setVehicle_lookAheadMinimum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double setVehicle_goalPointLookAheadMult {
            get {
                return ((double)(this["setVehicle_goalPointLookAheadMult"]));
            }
            set {
                this["setVehicle_goalPointLookAheadMult"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double stanleyDistanceErrorGain {
            get {
                return ((double)(this["stanleyDistanceErrorGain"]));
            }
            set {
                this["stanleyDistanceErrorGain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double stanleyHeadingErrorGain {
            get {
                return ((double)(this["stanleyHeadingErrorGain"]));
            }
            set {
                this["stanleyHeadingErrorGain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setVehicle_isStanleyUsed {
            get {
                return ((bool)(this["setVehicle_isStanleyUsed"]));
            }
            set {
                this["setVehicle_isStanleyUsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int setTram_BasedOn {
            get {
                return ((int)(this["setTram_BasedOn"]));
            }
            set {
                this["setTram_BasedOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int setTram_Skips {
            get {
                return ((int)(this["setTram_Skips"]));
            }
            set {
                this["setTram_Skips"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int setVehicle_vehicleType {
            get {
                return ((int)(this["setVehicle_vehicleType"]));
            }
            set {
                this["setVehicle_vehicleType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int set_youSkipWidth {
            get {
                return ((int)(this["set_youSkipWidth"]));
            }
            set {
                this["set_youSkipWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte setArdSteer_setting1 {
            get {
                return ((byte)(this["setArdSteer_setting1"]));
            }
            set {
                this["setArdSteer_setting1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte setArdSteer_minSpeed {
            get {
                return ((byte)(this["setArdSteer_minSpeed"]));
            }
            set {
                this["setArdSteer_minSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public byte setArdSteer_maxSpeed {
            get {
                return ((byte)(this["setArdSteer_maxSpeed"]));
            }
            set {
                this["setArdSteer_maxSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("56")]
        public byte setArdSteer_setting0 {
            get {
                return ((byte)(this["setArdSteer_setting0"]));
            }
            set {
                this["setArdSteer_setting0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double setVehicle_hydraulicLiftLookAhead {
            get {
                return ((double)(this["setVehicle_hydraulicLiftLookAhead"]));
            }
            set {
                this["setVehicle_hydraulicLiftLookAhead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setVehicle_isMachineControlToAutoSteer {
            get {
                return ((bool)(this["setVehicle_isMachineControlToAutoSteer"]));
            }
            set {
                this["setVehicle_isMachineControlToAutoSteer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public byte setArdSteer_maxPulseCounts {
            get {
                return ((byte)(this["setArdSteer_maxPulseCounts"]));
            }
            set {
                this["setArdSteer_maxPulseCounts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public byte setArdMac_hydRaiseTime {
            get {
                return ((byte)(this["setArdMac_hydRaiseTime"]));
            }
            set {
                this["setArdMac_hydRaiseTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public byte setArdMac_hydLowerTime {
            get {
                return ((byte)(this["setArdMac_hydLowerTime"]));
            }
            set {
                this["setArdMac_hydLowerTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte setArdMac_isHydEnabled {
            get {
                return ((byte)(this["setArdMac_isHydEnabled"]));
            }
            set {
                this["setArdMac_isHydEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte setArdMac_setting0 {
            get {
                return ((byte)(this["setArdMac_setting0"]));
            }
            set {
                this["setArdMac_setting0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte setArdSteer_setting2 {
            get {
                return ((byte)(this["setArdSteer_setting2"]));
            }
            set {
                this["setArdSteer_setting2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public double stanleyIntegralDistanceAwayTriggerAB {
            get {
                return ((double)(this["stanleyIntegralDistanceAwayTriggerAB"]));
            }
            set {
                this["stanleyIntegralDistanceAwayTriggerAB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double setVehicle_startSpeed {
            get {
                return ((double)(this["setVehicle_startSpeed"]));
            }
            set {
                this["setVehicle_startSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.9")]
        public double setVehicle_trackWidth {
            get {
                return ((double)(this["setVehicle_trackWidth"]));
            }
            set {
                this["setVehicle_trackWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setArdMac_isDanfoss {
            get {
                return ((bool)(this["setArdMac_isDanfoss"]));
            }
            set {
                this["setArdMac_isDanfoss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.15")]
        public double stanleyIntegralGainAB {
            get {
                return ((double)(this["stanleyIntegralGainAB"]));
            }
            set {
                this["stanleyIntegralGainAB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.15")]
        public double purePursuitIntegralGainAB {
            get {
                return ((double)(this["purePursuitIntegralGainAB"]));
            }
            set {
                this["purePursuitIntegralGainAB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public double set_youMoveDistance {
            get {
                return ((double)(this["set_youMoveDistance"]));
            }
            set {
                this["set_youMoveDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte setArdMac_user1 {
            get {
                return ((byte)(this["setArdMac_user1"]));
            }
            set {
                this["setArdMac_user1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public byte setArdMac_user2 {
            get {
                return ((byte)(this["setArdMac_user2"]));
            }
            set {
                this["setArdMac_user2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public byte setArdMac_user3 {
            get {
                return ((byte)(this["setArdMac_user3"]));
            }
            set {
                this["setArdMac_user3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public byte setArdMac_user4 {
            get {
                return ((byte)(this["setArdMac_user4"]));
            }
            set {
                this["setArdMac_user4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("56")]
        public byte setArdToolSteer_setting0 {
            get {
                return ((byte)(this["setArdToolSteer_setting0"]));
            }
            set {
                this["setArdToolSteer_setting0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string setVehicle_panicStopSpeed {
            get {
                return ((string)(this["setVehicle_panicStopSpeed"]));
            }
            set {
                this["setVehicle_panicStopSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double setVehicle_bndOverlap {
            get {
                return ((double)(this["setVehicle_bndOverlap"]));
            }
            set {
                this["setVehicle_bndOverlap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2,3,2")]
        public string Tool_SectionWidths {
            get {
                return ((string)(this["Tool_SectionWidths"]));
            }
            set {
                this["Tool_SectionWidths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public double Tool_Width {
            get {
                return ((double)(this["Tool_Width"]));
            }
            set {
                this["Tool_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Tool_Overlap {
            get {
                return ((double)(this["Tool_Overlap"]));
            }
            set {
                this["Tool_Overlap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-2.5")]
        public double Tool_TrailingHitchLength {
            get {
                return ((double)(this["Tool_TrailingHitchLength"]));
            }
            set {
                this["Tool_TrailingHitchLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Tool_numSections {
            get {
                return ((int)(this["Tool_numSections"]));
            }
            set {
                this["Tool_numSections"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Tool_isTooLSteering {
            get {
                return ((bool)(this["Tool_isTooLSteering"]));
            }
            set {
                this["Tool_isTooLSteering"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public byte Tool_maxSteerAngle {
            get {
                return ((byte)(this["Tool_maxSteerAngle"]));
            }
            set {
                this["Tool_maxSteerAngle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public byte Tool_wasCounts {
            get {
                return ((byte)(this["Tool_wasCounts"]));
            }
            set {
                this["Tool_wasCounts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127")]
        public byte Tool_wasOffset {
            get {
                return ((byte)(this["Tool_wasOffset"]));
            }
            set {
                this["Tool_wasOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public byte Tool_HighPWM {
            get {
                return ((byte)(this["Tool_HighPWM"]));
            }
            set {
                this["Tool_HighPWM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte Tool_windupLimit {
            get {
                return ((byte)(this["Tool_windupLimit"]));
            }
            set {
                this["Tool_windupLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public byte Tool_P {
            get {
                return ((byte)(this["Tool_P"]));
            }
            set {
                this["Tool_P"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte Tool_MinPWM {
            get {
                return ((byte)(this["Tool_MinPWM"]));
            }
            set {
                this["Tool_MinPWM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte Tool_I {
            get {
                return ((byte)(this["Tool_I"]));
            }
            set {
                this["Tool_I"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Tool_antennaHeight {
            get {
                return ((double)(this["Tool_antennaHeight"]));
            }
            set {
                this["Tool_antennaHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Tool_antennaOffset {
            get {
                return ((double)(this["Tool_antennaOffset"]));
            }
            set {
                this["Tool_antennaOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double Tool_defaultSectionWidth {
            get {
                return ((double)(this["Tool_defaultSectionWidth"]));
            }
            set {
                this["Tool_defaultSectionWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Tool_OffDelay {
            get {
                return ((double)(this["Tool_OffDelay"]));
            }
            set {
                this["Tool_OffDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Tool_isToolFront {
            get {
                return ((bool)(this["Tool_isToolFront"]));
            }
            set {
                this["Tool_isToolFront"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Tool_isTBT {
            get {
                return ((bool)(this["Tool_isTBT"]));
            }
            set {
                this["Tool_isTBT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double Tool_LookAheadOn {
            get {
                return ((double)(this["Tool_LookAheadOn"]));
            }
            set {
                this["Tool_LookAheadOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Tool_isTrailing {
            get {
                return ((bool)(this["Tool_isTrailing"]));
            }
            set {
                this["Tool_isTrailing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Tool_Offset {
            get {
                return ((double)(this["Tool_Offset"]));
            }
            set {
                this["Tool_Offset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double Tool_LookAheadOff {
            get {
                return ((double)(this["Tool_LookAheadOff"]));
            }
            set {
                this["Tool_LookAheadOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-3")]
        public double Tool_TankTrailingHitchLength {
            get {
                return ((double)(this["Tool_TankTrailingHitchLength"]));
            }
            set {
                this["Tool_TankTrailingHitchLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Tool_minCoverage {
            get {
                return ((int)(this["Tool_minCoverage"]));
            }
            set {
                this["Tool_minCoverage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Tool_isToolRearFixed {
            get {
                return ((bool)(this["Tool_isToolRearFixed"]));
            }
            set {
                this["Tool_isToolRearFixed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Tool_Section_isFast {
            get {
                return ((bool)(this["Tool_Section_isFast"]));
            }
            set {
                this["Tool_Section_isFast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double Tool_slowSpeedCutoff {
            get {
                return ((double)(this["Tool_slowSpeedCutoff"]));
            }
            set {
                this["Tool_slowSpeedCutoff"] = value;
            }
        }
    }
}
