//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgIO.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GPS**")]
        public string setPort_portNameGPS {
            get {
                return ((string)(this["setPort_portNameGPS"]));
            }
            set {
                this["setPort_portNameGPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int setPort_baudRateGPS {
            get {
                return ((int)(this["setPort_baudRateGPS"]));
            }
            set {
                this["setPort_baudRateGPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setUDP_isOn {
            get {
                return ((bool)(this["setUDP_isOn"]));
            }
            set {
                this["setUDP_isOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("69.75.31.235")]
        public string setNTRIP_casterIP {
            get {
                return ((string)(this["setNTRIP_casterIP"]));
            }
            set {
                this["setNTRIP_casterIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2101")]
        public int setNTRIP_casterPort {
            get {
                return ((int)(this["setNTRIP_casterPort"]));
            }
            set {
                this["setNTRIP_casterPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IGS01")]
        public string setNTRIP_mount {
            get {
                return ((string)(this["setNTRIP_mount"]));
            }
            set {
                this["setNTRIP_mount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setNTRIP_userName {
            get {
                return ((string)(this["setNTRIP_userName"]));
            }
            set {
                this["setNTRIP_userName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setNTRIP_userPassword {
            get {
                return ((string)(this["setNTRIP_userPassword"]));
            }
            set {
                this["setNTRIP_userPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setNTRIP_isOn {
            get {
                return ((bool)(this["setNTRIP_isOn"]));
            }
            set {
                this["setNTRIP_isOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int setNTRIP_sendGGAInterval {
            get {
                return ((int)(this["setNTRIP_sendGGAInterval"]));
            }
            set {
                this["setNTRIP_sendGGAInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2233")]
        public int setNTRIP_sendToUDPPort {
            get {
                return ((int)(this["setNTRIP_sendToUDPPort"]));
            }
            set {
                this["setNTRIP_sendToUDPPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("53")]
        public double setNTRIP_manualLat {
            get {
                return ((double)(this["setNTRIP_manualLat"]));
            }
            set {
                this["setNTRIP_manualLat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-111")]
        public double setNTRIP_manualLon {
            get {
                return ((double)(this["setNTRIP_manualLon"]));
            }
            set {
                this["setNTRIP_manualLon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("www.rtk2go.com")]
        public string setNTRIP_casterURL {
            get {
                return ((string)(this["setNTRIP_casterURL"]));
            }
            set {
                this["setNTRIP_casterURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setNTRIP_isGGAManual {
            get {
                return ((bool)(this["setNTRIP_isGGAManual"]));
            }
            set {
                this["setNTRIP_isGGAManual"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setNTRIP_isTCP {
            get {
                return ((bool)(this["setNTRIP_isTCP"]));
            }
            set {
                this["setNTRIP_isTCP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setNTRIP_isHTTP10 {
            get {
                return ((bool)(this["setNTRIP_isHTTP10"]));
            }
            set {
                this["setNTRIP_isHTTP10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setPgm_isFirstRun {
            get {
                return ((bool)(this["setPgm_isFirstRun"]));
            }
            set {
                this["setPgm_isFirstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double setPgm_defaultLat {
            get {
                return ((double)(this["setPgm_defaultLat"]));
            }
            set {
                this["setPgm_defaultLat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double setPgm_defaultLon {
            get {
                return ((double)(this["setPgm_defaultLon"]));
            }
            set {
                this["setPgm_defaultLon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string setF_culture {
            get {
                return ((string)(this["setF_culture"]));
            }
            set {
                this["setF_culture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string setF_workingDirectory {
            get {
                return ((string)(this["setF_workingDirectory"]));
            }
            set {
                this["setF_workingDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setPort_wasGPSConnected {
            get {
                return ((bool)(this["setPort_wasGPSConnected"]));
            }
            set {
                this["setPort_wasGPSConnected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("***")]
        public string setPort_portNameRadio {
            get {
                return ((string)(this["setPort_portNameRadio"]));
            }
            set {
                this["setPort_portNameRadio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public string setPort_baudRateRadio {
            get {
                return ((string)(this["setPort_baudRateRadio"]));
            }
            set {
                this["setPort_baudRateRadio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("439.000")]
        public string setPort_radioChannel {
            get {
                return ((string)(this["setPort_radioChannel"]));
            }
            set {
                this["setPort_radioChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setRadio_isOn {
            get {
                return ((bool)(this["setRadio_isOn"]));
            }
            set {
                this["setRadio_isOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<AgIO.CRadioChannel> setRadio_Channels {
            get {
                return ((global::System.Collections.Generic.List<AgIO.CRadioChannel>)(this["setRadio_Channels"]));
            }
            set {
                this["setRadio_Channels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setUDP_isSendNMEAToUDP {
            get {
                return ((bool)(this["setUDP_isSendNMEAToUDP"]));
            }
            set {
                this["setUDP_isSendNMEAToUDP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GGA")]
        public string setGPS_lastSentence {
            get {
                return ((string)(this["setGPS_lastSentence"]));
            }
            set {
                this["setGPS_lastSentence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RTCM")]
        public string setPort_portNameRtcm {
            get {
                return ((string)(this["setPort_portNameRtcm"]));
            }
            set {
                this["setPort_portNameRtcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int setPort_baudRateRtcm {
            get {
                return ((int)(this["setPort_baudRateRtcm"]));
            }
            set {
                this["setPort_baudRateRtcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setPort_wasRtcmConnected {
            get {
                return ((bool)(this["setPort_wasRtcmConnected"]));
            }
            set {
                this["setPort_wasRtcmConnected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setUDP_isUsePluginApp {
            get {
                return ((bool)(this["setUDP_isUsePluginApp"]));
            }
            set {
                this["setUDP_isUsePluginApp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setNTRIP_sendToSerial {
            get {
                return ((bool)(this["setNTRIP_sendToSerial"]));
            }
            set {
                this["setNTRIP_sendToSerial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setNTRIP_sendToUDP {
            get {
                return ((bool)(this["setNTRIP_sendToUDP"]));
            }
            set {
                this["setNTRIP_sendToUDP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("256")]
        public int setNTRIP_packetSize {
            get {
                return ((int)(this["setNTRIP_packetSize"]));
            }
            set {
                this["setNTRIP_packetSize"] = value;
            }
        }
    }
}
